### ISSUE TITLE
Relative paths in parserOptions not supported

### ISSUE THREAD

**Issue by kopischke** [kopischke/microESLint.nova#2]
As described for the Typescript ESLint parser in #1, setting `cwd` to the linted file’s containing directory breaks linting when the ESLint parser configuration expects the current working directory to be its own containing directory. As the solution in the PR [would break common linting scenarios](https://github.com/kopischke/microESLint.nova/pull/1#issuecomment-730264784), we need a different one.

**Comment by kopischke** [comment]
My current thinking would be to set ESLint’s `cwd` to the directory containing the closest config to the file being linted. This should solve all cases of relative paths in config files where there is only one config file in the hierarchy. The hitch with this is that I am bit what this means for cascading configs with relative paths. To my understanding, relative paths in config files are an explicit expectation  that the `cwd` running ESLint is the config file’s containing directory. If that assumption is correct, cascading configs do not work in theses scenarios anyway, and we lose zero effective functionality with my proposed solution.

@natesilva, can I bother you for your input: is it possible to create a cascading config with your setup, i.e. add a sub-config in some subdirectory refining the rules without explicitly restating the (suitable modified) path in `parserOptions`?

Also, you mentioned file paths must be relative to the config root in your usage case. Have you tested that independently from setting the ESLint `cwd` to your project root? In my testing, ESLint could not care less for the file path format, as long as it runs in a directory where it has correct access to its config hierarchy.

**Comment by kopischke** [comment]
@natesilva I’ve pushed the [fix/eslint-cwd](https://github.com/kopischke/microESLint.nova/tree/fix/eslint-cwd) branch. As a first step, it implements setting `cwd` to the directory containing the ESLint config file closest to the file to lint in the hierarchy. Would you mind taking it for a test drive, report if it solves your issue, and post the console output if it does not?

**Comment by kopischke** [comment]
@natesilva I am teribly sorry to be a bother, but I have been testing my fix for a while now without hitches, and as I have a number of other bugfixes and minor improvements lined up for the next update (those are not pushed on the branch), I was wondering if you had any chance to check it out too? Or, if you are pressed for time – which I’d fully understand, you are not at the beck and call of some stranger –, if you could point me to a project I could use to test it myself?

**Comment by natesilva** [comment]
Hi @kopischke. Sorry for the delay. I’m testing the `fix/eslint-cwd` branch now.

**Comment by natesilva** [comment]
This is still not linting my project. I’ve attached a stripped-down example, see `src/app.ts` for info. I did try editing my `.eslintrc` as you suggested, by setting an absolute path. That didn’t fix it though. :-/

[example.tar.gz](https://github.com/kopischke/microESLint.nova/files/5585307/example.tar.gz)

**Comment by natesilva** [comment]
I would like to correct something I said earlier: In `.eslintrc`, changing the `tsconfigRootDir` to `/Volumes/Macintosh HD/Users/nate/Downloads/example` does work. Notice that you have to add `/Volumes/Macintosh HD/` ahead of your root path.

**Comment by natesilva** [comment]
Aha! One more comment and then I’ll shut up. 😬

💡 If you remove `/Volumes/Macintosh HD` leading the path, then it works, as far as I can tell.

**Comment by kopischke** [comment]
Thanks a lot for this! The example project has proven tremendously helpful; with that and your notes, I have managed to piece together what happens. As it turns out, there are **two** distinct issues at play here:

1. The one tracked right here, i.e. that relative `parseOptions` references will break linting when ESLint’s working directory is different from the one containing the config file. The good news is that the [fix/eslint-cwd](https://github.com/kopischke/microESLint.nova/tree/fix/eslint-cwd) branch fixes that specific issue.
2. The fact the TypeScript ESLint parser cannot handle the path convention peculiar to Macs. As background: `/Volumes/<Drive name (defaults to “Macintosh HD”)>` is the canonical HFS root path on Macs returned by Nova’s file management APIs. The problem seems to be the drive name is actually a symbolic link to the UNIX root path `/`, and that seems to throw some tools with a more naive approach to path handling. This will be tracked in #3.

A related problem that obscured this is that ESLint [outputs all parsing errors as “fatal” linting errors](https://github.com/eslint/eslint/blob/82669fa66670a00988db5b1d10fe8f3bf30be84e/lib/linter/linter.js#L648-L651) – not as execution errors. Because a lot of these are not helpful at all, _µESLint_ filters them out, which means it just looks as if it does nothing in your scenario. I was aware this could happen (see this [comment](https://github.com/kopischke/microESLint.nova/blob/4b80f3423e865608b5d4ee9bc11973c3f8dd2fb7/%C2%B5ESLint.novaextension/Scripts/core/issues.js#L25-L27)), and I am not sure it makes sense to change this (because that means you’d get spurious parsing errors when opening, say, an XML file), but it admittedly is not an optimal user facing scenario in your case.
